### PR TITLE
add CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by chanshing**
To fulfill https://github.com/activityMonitoring/biobankAccelerometerAnalysis/issues/115

This adds CONTRIBUTING.md &mdash; guide on how to contribute to this repo.

Feedback appreciated. Feel free to suggest your own recommendations! :dancing_men: 

To review, it helps to put the file into a markdown viewer like https://markdownlivepreview.com/ or click on this button in Github:
prmarkdownview

### CODE REVIEW

**Comment by angerhang** [comment]
Hi Shing, this looks fantastic! Thanks for all the work! Just two minor suggestions:
1. https://stackoverflow.com/questions/5319754/cross-reference-named-anchor-in-markdown it might be good to have Table of Contents by using the anchor in the beginning for the ease of navigation because it is loaded with lots of great information :D 
2. It is great that we have a very good walk through for how to submit a PR but not sure if might be too detailed? Feel free to disagree with me this one as I feel it could benefit many people who are new to open source projects ;D

**Review by angerhang — APPROVED** [review]

**Comment by R-Walmsley** [comment]
Hi @chanshing, 

This looks great!

Comments: 
- I agree with @angerhang that a Table of Contents would be really useful. 
- I disagree with @angerhang that it's too detailed. I think that's really helpful, especially for people just starting out (who might be really useful contributors). 
- I wonder if we want to mention anything about testing and our vision for that going forwards. Should we at least say how it's tested currently? Because it's very easy to break (and correctly so) in PRs. 
- Two typos: 'worflow' [line 32], 'a follows' [line 176] 
- If we eventually intend to update to the new GitHub naming convention (i.e. `main` not `master`), is this a good time to do it, as it potentially widens up the audience and especially the contributing audience? I did this on a repo recently and I was pleasantly surprised by how easy it was - although it is obviously trickier for a repo for which there are many forks and clones. 
- On commit messages, I like the rule: your commit message should finish the sentence, "If merged, this commit will..." Obviously says the same as you say, but might be more memorable? [I don't have a strong opinion]. 
- I appreciated the suggestion to drink tea :)

**Review by R-Walmsley — APPROVED** [review]

**Comment by chanshing** [comment]
Thank you both for your great feedback!
- ToC added
- Info on PR automatic checks added

Thanks @angerhang for your feedback. I also thought maybe such a thorough description of the workflow is out of scope, but as a git newbie I wished I had all the information in one place. When learning git and its many contradicting workflows I felt that the resources were scattered all over the internet.
Thanks @R-Walmsley for spotting the typos and the great suggestions. Regarding `master`/`main`, I agree with the change, but maybe we should open a separate issue?

**Comment by R-Walmsley** [comment]
Just opened #126 👍

**Pull request merged**
