### PR TITLE
add clipsBefore/AfterCalibr and total reads to the summary.

### PR DESCRIPTION
**Pull request by R-Walmsley**
This only adds the extra outputs. Tests will be added in a separate PR (separating the elements of PR #77 ).

### CODE REVIEW

**Comment by angerhang** [comment]
Thx for the great work Rosemary. Hmm I am just a bit confused. I think it would have been OK for the tests and the features changes to land in the same PR otherwise how would we know the changes being made are for certain correct except for eyeballing them? :D

**Comment by R-Walmsley** [comment]
We're not yet adding unit tests for those features, we're adding an overall regression test for the output? Of which this is only 1 tiny aspect, so in my head it made sense to separate them... Happy to be overruled on this though!

**Comment by R-Walmsley** [comment]
Actually maybe the best thing is to leave this unmerged until we've merged the regression test, then we will check it? 
I'm just having more trouble with the test!

**Comment by R-Walmsley** [comment]
@angerhang  - I'd like to merge this then immediately merge the regression test on top of this? Is that ok with you?

**Pull request merged**
