### PR TITLE
allow display of activity classification during imputed period of time

### PR DESCRIPTION
**Pull request by xiangnandang**
…imputed period of time

### CODE REVIEW

**Comment by xiangnandang** [comment]
Hi,

This pull request is to address this requirement in the output plots: during imputed period, the only information readable from the plot is that this period of time is imputed, but not about the imputed activity classification.

The current pull request provides a naive solution to use roughly bottom 50% to display activity classification for both imputed and non-imputed period of time (just the entire time), and use the top 50% to highlight the imputed period. The outcome is as this graph (showing one day and the early morning period is imputed):

image

During imputed period, the relative bar graph height indicate the possibility of activity classification as originally designed, noting the probabilities not always add to 1, could this be a rounding issue during imputation for activity classification?

I hope this helps in general to display both imputation flag as well as imputation result in the output. The 50% bottom and 50% top could either be changed to a better default, or supplied as an argument (I don't think that's quite necessary).

Best,
Xiangnan

**Comment by chanshing** [comment]
Thanks for your contribution. I am not sure about this. @aidendoherty @R-Walmsley @angerhang what do you think?

**Comment by xiangnandang** [comment]
@chanshing , thanks for your comment. I absolutely see that this option should not be the default, so maybe add as an argument to allow advanced users to see more details into imputed periods?

Best,
Xiangann

**Comment by angerhang** [comment]
I think the option is nice to have but maybe too wasteful in terms of space usage. Maybe we should change the ratio to 80%-20% or 70%-30%.

**Comment by xiangnandang** [comment]
@angerhang , I agree about the ratio. I'll later make it a true/false argument for the call, with default as false, and set the the ratio to 25%.

**Comment by xiangnandang** [comment]
added --imputedLabels as an argument to control this behavior, and default to False, plotting as original:
image

if --imputedLabels True, then plot with top 25% area as indicator for imputation, and bottom 75% area to plot imputed activity classification 
image

Best,
Xiangnan

**Comment by aidendoherty** [comment]
This code is very useful. Many thanks @xiangnandang !
Also many thanks @chanshing and @angerhang for your comments and feedback - it is very much appreciated.

**Pull request merged**
