### PR TITLE
Add Junit tests framework 

### PR DESCRIPTION
**Pull request by angerhang**
* The Junit testing workflow
* Sample unit test
* Timestamp conversion for gt3x v2
* Regression tests to parse gt3x v2 and checking the content against a template csv file

### CODE REVIEW

**Review by R-Walmsley — COMMENTED** [review]
Some general comments (with the caveat I'm not very familiar with the Java code, so am of limited use): 

- Do we want to just test on Ubuntu? Or other OS? I assume most people using it will need to be using Linux-based systems, but am not sure, and it makes sense to agree a policy on this now. 
- Is it possible to add to the README.md something saying what each test does? Just thinking by the time there are many tests it would be useful to be able to quickly check what tests which are failing relate to?
- At the moment I read the README as suggesting that to run the tests you have to run them locally. Might be worth adding a sentence to say they're automatically run when you push or submit a PR?

**Comment by angerhang** [comment]
> Some general comments (with the caveat I'm not very familiar with the Java code, so am of limited use):
> 
> * Do we want to just test on Ubuntu? Or other OS? I assume most people using it will need to be using Linux-based systems, but am not sure, and it makes sense to agree a policy on this now.
> * Is it possible to add to the README.md something saying what each test does? Just thinking by the time there are many tests it would be useful to be able to quickly check what tests which are failing relate to?
> * At the moment I read the README as suggesting that to run the tests you have to run them locally. Might be worth adding a sentence to say they're automatically run when you push or submit a PR?

Thanks for the feedback :D 

Concerning OS, I am not sure if we are supporting Windows right now since all the paths in the documentations are in Linux style anyway. Maybe @chanshing @aidendoherty can commet on this.

For the descriptions of each test, maybe it would be good to add that in the workflow file for each test which I will do later.

Concerning the last point, perhaps we should make it clear that it is best to stick with a test-driven development process that for all the new and testable code, one should add the unit tests and test them locally. The CI integration is really just a matter for sanity check and shall not be as the primary way to run those tests :D But I would modify the README to make them more clear.

**Comment by R-Walmsley** [comment]
> Concerning OS, I am not sure if we are supporting Windows right now since all the paths in the documentations are in Linux style anyway. Maybe @chanshing @aidendoherty can commet on this.

All of that makes sense, and in particular I agree on OS - would be good to clarify with @aidendoherty whether this is an explicit policy.

**Comment by chanshing** [comment]
Hi Hang. All looks very good. My major comments are: 

1. Maybe we should follow the Github workflow? (the link shared by Aiden https://gist.github.com/Chaser324/ce0505fbed06b947d962). Basically, do as if you didn't have write permissions to this repo:
    1. Fork this repository
    2. Create a branch in _your fork_ that solves a specific issue, say `fix-timestamps-dst`.
    3. Work on your branch in your fork. Once done, submit the PR to merge this repo's master to your fork's branch.
I believe this is the standard way in Github. I had to follow this as well when I wanted to submit something to [PyTorch](https://github.com/pytorch/pytorch) :fire:
2. I think I spotted a few changes in this PR related to solving the timestamps issue. Would be good to separate these :scissors: 
3. Maybe we could squash some of the commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html :art:

**Comment by angerhang** [comment]
> Hi Hang. All looks very good. My major comments are:
> 
> 1. Maybe we should follow the Github workflow? (the link shared by Aiden https://gist.github.com/Chaser324/ce0505fbed06b947d962). Basically, do as if you didn't have write permissions to this repo:
>    
>    1. Fork this repository
>    2. Create a branch in _your fork_ that solves a specific issue, say `fix-timestamps-dst`.
>    3. Work on your branch in your fork. Once done, submit the PR to merge this repo's master to your fork's branch.
>       I believe this is the standard way in Github. I had to follow this as well when I wanted to submit something to [PyTorch](https://github.com/pytorch/pytorch) 🔥
> 2. I think I spotted a few changes in this PR related to solving the timestamps issue. Would be good to separate these ✂️
> 3. Maybe we could squash some of the commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html 🎨
> 
> Some other useful pointers:
> 
> * Commit messages best practice (borrowed from Java Spring) https://github.com/spring-projects/spring-framework/blob/30bce7/CONTRIBUTING.md#format-commit-messages The link also contains other tips I found helpful
> * PR best  practices https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests
> 
> It's probably a pain to follow all these but I think it's gonna be a great time saver in the long run 👯 What do you think? @angerhang @R-Walmsley @aidendoherty

Hi Shing thanks for the comments. So I ruined the comment history when I was trying to squash the commit messages :( So I had to manually recreate two new branches. Anyway, I agree with most of the points your mentioned ;D Please see two clean PRs https://github.com/activityMonitoring/biobankAccelerometerAnalysis/pull/65 https://github.com/activityMonitoring/biobankAccelerometerAnalysis/pull/66 for the testings and gt3x separately.

One thing that I might agree with is how we do PR, I think the workflow you proposed is good for the outside contributors but for us, I think it would be much more convenient to just create branches such that we don't have to track two upstreams. Sometimes having to work using a fork make syncing and merging more troublesome than they might seem. I don't really see any strong reasons for not using branches to do PR but to use separate forks. Imagine if we all have different forks ourselves, then if want to test others' experimental feature or code, we will have to have multiple copies of the repo for different developers :D 

Anyway, closing this PR as it is no longer needed.

**Comment by chanshing** [comment]
> > Hi Hang. All looks very good. My major comments are:
> > 
> > 1. Maybe we should follow the Github workflow? (the link shared by Aiden https://gist.github.com/Chaser324/ce0505fbed06b947d962). Basically, do as if you didn't have write permissions to this repo:
> >    
> >    1. Fork this repository
> >    2. Create a branch in _your fork_ that solves a specific issue, say `fix-timestamps-dst`.
> >    3. Work on your branch in your fork. Once done, submit the PR to merge this repo's master to your fork's branch.
> >       I believe this is the standard way in Github. I had to follow this as well when I wanted to submit something to [PyTorch](https://github.com/pytorch/pytorch) fire
> > 2. I think I spotted a few changes in this PR related to solving the timestamps issue. Would be good to separate these scissors
> > 3. Maybe we could squash some of the commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html art
> > 
> > Some other useful pointers:
> > 
> > * Commit messages best practice (borrowed from Java Spring) https://github.com/spring-projects/spring-framework/blob/30bce7/CONTRIBUTING.md#format-commit-messages The link also contains other tips I found helpful
> > * PR best  practices https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests
> > 
> > It's probably a pain to follow all these but I think it's gonna be a great time saver in the long run dancers What do you think? @angerhang @R-Walmsley @aidendoherty
> 
> Hi Shing thanks for the comments. So I ruined the comment history when I was trying to squash the commit messages :( So I had to manually recreate two new branches. Anyway, I agree with most of the points your mentioned ;D Please see two clean PRs #65 #66 for the testings and gt3x separately.
> 
> One thing that I might agree with is how we do PR, I think the workflow you proposed is good for the outside contributors but for us, I think it would be much more convenient to just create branches such that we don't have to track two upstreams. Sometimes having to work using a fork make syncing and merging more troublesome than they might seem. I don't really see any strong reasons for not using branches to do PR but to use separate forks. Imagine if we all have different forks ourselves, then if want to test others' experimental feature or code, we will have to have multiple copies of the repo for different developers :D
> 
> Anyway, closing this PR as it is no longer needed.

Thanks Hang. The problem you faced is the exact reason for working on a separate fork! I don't see it's that troublesome to keep track of two upstreams. I mean, this is what all other repositories do. Maybe we should follow best practice? What do you think? @angerhang

**Comment by chanshing** [comment]
> > Hi Hang. All looks very good. My major comments are:
> > 
> > 1. Maybe we should follow the Github workflow? (the link shared by Aiden https://gist.github.com/Chaser324/ce0505fbed06b947d962). Basically, do as if you didn't have write permissions to this repo:
> >    
> >    1. Fork this repository
> >    2. Create a branch in _your fork_ that solves a specific issue, say `fix-timestamps-dst`.
> >    3. Work on your branch in your fork. Once done, submit the PR to merge this repo's master to your fork's branch.
> >       I believe this is the standard way in Github. I had to follow this as well when I wanted to submit something to [PyTorch](https://github.com/pytorch/pytorch) fire
> > 2. I think I spotted a few changes in this PR related to solving the timestamps issue. Would be good to separate these scissors
> > 3. Maybe we could squash some of the commits http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html art
> > 
> > Some other useful pointers:
> > 
> > * Commit messages best practice (borrowed from Java Spring) https://github.com/spring-projects/spring-framework/blob/30bce7/CONTRIBUTING.md#format-commit-messages The link also contains other tips I found helpful
> > * PR best  practices https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests
> > 
> > It's probably a pain to follow all these but I think it's gonna be a great time saver in the long run dancers What do you think? @angerhang @R-Walmsley @aidendoherty
> 
> Hi Shing thanks for the comments. So I ruined the comment history when I was trying to squash the commit messages :( So I had to manually recreate two new branches. Anyway, I agree with most of the points your mentioned ;D Please see two clean PRs #65 #66 for the testings and gt3x separately.
> 
> One thing that I might agree with is how we do PR, I think the workflow you proposed is good for the outside contributors but for us, I think it would be much more convenient to just create branches such that we don't have to track two upstreams. Sometimes having to work using a fork make syncing and merging more troublesome than they might seem. I don't really see any strong reasons for not using branches to do PR but to use separate forks. Imagine if we all have different forks ourselves, then if want to test others' experimental feature or code, we will have to have multiple copies of the repo for different developers :D
> 
> Anyway, closing this PR as it is no longer needed.

Hi Hang. Just saw your reply on Github. Posting my reply here as well Big smile

The problem you faced is the exact reason for working on a separate fork!: It's good to have one more layer of protection between your work and the main repo, then if you screw up something like now you can freely change things in your own fork. Another is that if every contributor were to open branches in the main repo it can get very messy very fast (specially for very large projects with many "internal" contributors; although Github doesn't distinguish such thing Big smile
)

I hope this workflow will become easier with time, and it's also good training for future teams as this is what most other projects ask you to do. It's also the default mode in Github (when you click 'Edit' on a repo code, it will first fork the repo for you then create a branch patch-1).
. Even if we are a small group, I think it is a good exercise to follow best practice? What do you think? @angerhang @R-Walmsley @aidendoherty

**Pull request closed without merging**
